#pragma once

#ifdef _WIN32
#include <windows.h>
#include <guiddef.h>
#include <winioctl.h>

/* 5a09f9e5-7d62-4a65-bce8-d0d9830eb27c */
DEFINE_GUID(GUID_DEVINTERFACE_GDRIVER_CAPTURE,
            0x5a09f9e5, 0x7d62, 0x4a65, 0xbc, 0xe8, 0xd0, 0xd9, 0x83, 0x0e, 0xb2, 0x7c);

#ifndef FILE_DEVICE_GDRIVER_CAPTURE
#define FILE_DEVICE_GDRIVER_CAPTURE 0x8337u
#endif

#define GDRIVER_IOCTL(index, method, access) \
    CTL_CODE(FILE_DEVICE_GDRIVER_CAPTURE, (index), (method), (access))

#define IOCTL_GDRIVER_GET_ABI_VERSION \
    GDRIVER_IOCTL(0x800u, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_GDRIVER_GET_DEVICE_INFO \
    GDRIVER_IOCTL(0x801u, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_GDRIVER_GET_CAPABILITIES \
    GDRIVER_IOCTL(0x802u, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_GDRIVER_SET_INPUT \
    GDRIVER_IOCTL(0x803u, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_GDRIVER_CONFIGURE_STREAM \
    GDRIVER_IOCTL(0x804u, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_GDRIVER_START_STREAM \
    GDRIVER_IOCTL(0x805u, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_GDRIVER_STOP_STREAM \
    GDRIVER_IOCTL(0x806u, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_GDRIVER_WAIT_FRAME \
    GDRIVER_IOCTL(0x807u, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_GDRIVER_RELEASE_FRAME \
    GDRIVER_IOCTL(0x808u, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_GDRIVER_GET_SIGNAL_STATUS \
    GDRIVER_IOCTL(0x809u, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_GDRIVER_GET_STATS \
    GDRIVER_IOCTL(0x80au, METHOD_BUFFERED, FILE_READ_ACCESS)
#endif
